name: "ant CI workflow macos"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ dev ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-ant
  build-macos-job:
    name: "Set up JDK 1.8 on macos-latest 10.15.7"
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64        
    - name: "Verify ant version"
      run: ant -v 
    - name: "Verify ant version"
      run: ant -version         
    # - name: "Build with Ant"
    #   run: ant -noinput -buildfile build.xml     
    # - name: "Run the Ant jar target"
    #   run: ant -noinput -buildfile build-ci.xml jar       


     
