name: "ant CI workflow ubuntu"

on:
  push:
    # branches: [ $default-branch ]
    branches: [ dev ]
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  
# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-ant
  build-linux-job:
    name: "Specifying the JVM version and architecture on ubuntu-18.04"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "Set up JDK 9.0.4 for x64"
      uses: actions/setup-java@v1
      with:
          java-version: '9.0.4'
          architecture: x64   
    - name: "Verify ant version"
      run: ant -version
    - name: "build from the command line(ant -f)"
      run: ant -f build.xml     
    - name: "build from the command line (ant)"
      run: ant  
    - name: "build from the command line (ant -noinput -buildfile)"
      run: ant -noinput -buildfile build.xml                     
    # - name: "Build with Ant"
    #   run: ant -noinput -buildfile build.xml
    # - name: "Run the Ant jar target"
    #   run: ant -noinput -buildfile build-ci.xml jar


 

# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
  build-linux-packing-job:
    name: "Caching dependencies on ubuntu-18.04"
    runs-on: ubuntu-latest #ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: "Set up JDK 1.8"
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        architecture: x64  
    - run: ant -noinput -buildfile build.xml
    - uses: actions/upload-artifact@v2
      with:
        name: "Package"
        path: build/jar

     
